/**
 * TollGuru Calculator
 * TollGuru Calculator API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 2020-05-31T17:48:12Z
 * Contact: eng@tollguru.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Location from './Location';

/**
* The AllOfGmapRequestBodyFrom model module.
* @module model/AllOfGmapRequestBodyFrom
* @version 2020-05-31T17:48:12Z
*/
export default class AllOfGmapRequestBodyFrom {
    /**
    * Constructs a new <code>AllOfGmapRequestBodyFrom</code>.
    * @alias module:model/AllOfGmapRequestBodyFrom
    * @class
    * @extends module:model/Location
    */

    constructor() {
        Location.call(this);
        
        
    }

    /**
    * Constructs a <code>AllOfGmapRequestBodyFrom</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AllOfGmapRequestBodyFrom} obj Optional instance to populate.
    * @return {module:model/AllOfGmapRequestBodyFrom} The populated <code>AllOfGmapRequestBodyFrom</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AllOfGmapRequestBodyFrom();
            
            Location.constructFromObject(data, obj);
            
        }
        return obj;
    }





}
