/**
 * TollGuru Calculator
 * TollGuru Calculator API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 2020-05-31T17:48:12Z
 * Contact: eng@tollguru.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import HosReq from './HosReq';

/**
* The AllOfHereRequestBodyHos model module.
* @module model/AllOfHereRequestBodyHos
* @version 2020-05-31T17:48:12Z
*/
export default class AllOfHereRequestBodyHos {
    /**
    * Constructs a new <code>AllOfHereRequestBodyHos</code>.
    * @alias module:model/AllOfHereRequestBodyHos
    * @class
    * @extends module:model/HosReq
    */

    constructor() {
        HosReq.call(this);
        
        
    }

    /**
    * Constructs a <code>AllOfHereRequestBodyHos</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AllOfHereRequestBodyHos} obj Optional instance to populate.
    * @return {module:model/AllOfHereRequestBodyHos} The populated <code>AllOfHereRequestBodyHos</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AllOfHereRequestBodyHos();
            
            HosReq.constructFromObject(data, obj);
            
        }
        return obj;
    }





}
