/**
 * TollGuru Calculator
 * TollGuru Calculator API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 2020-05-31T17:48:12Z
 * Contact: eng@tollguru.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The AsyncResponse model module.
* @module model/AsyncResponse
* @version 2020-05-31T17:48:12Z
*/
export default class AsyncResponse {
    /**
    * Constructs a new <code>AsyncResponse</code>.
    * @alias module:model/AsyncResponse
    * @class
    */

    constructor() {
        
        OneOfinlineResponse2001.call(this);
        
    }

    /**
    * Constructs a <code>AsyncResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AsyncResponse} obj Optional instance to populate.
    * @return {module:model/AsyncResponse} The populated <code>AsyncResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AsyncResponse();
                        
            
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('requestId')) {
                obj['requestId'] = ApiClient.convertToType(data['requestId'], 'String');
            }
            if (data.hasOwnProperty('requestedTimestamp')) {
                obj['requestedTimestamp'] = ApiClient.convertToType(data['requestedTimestamp'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} status
    */
    'status' = undefined;
    /**
    * @member {String} requestId
    */
    'requestId' = undefined;
    /**
    * @member {String} requestedTimestamp
    */
    'requestedTimestamp' = undefined;

    // Implement OneOfinlineResponse2001 interface:
    


}
