/**
 * TollGuru Calculator
 * TollGuru Calculator API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 2020-05-31T17:48:12Z
 * Contact: eng@tollguru.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DirectionPosition from './DirectionPosition';

/**
* The Direction model module.
* @module model/Direction
* @version 2020-05-31T17:48:12Z
*/
export default class Direction {
    /**
    * Constructs a new <code>Direction</code>.
    * @alias module:model/Direction
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Direction</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Direction} obj Optional instance to populate.
    * @return {module:model/Direction} The populated <code>Direction</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Direction();
                        
            
            if (data.hasOwnProperty('position')) {
                obj['position'] = DirectionPosition.constructFromObject(data['position']);
            }
            if (data.hasOwnProperty('maneuver')) {
                obj['maneuver'] = ApiClient.convertToType(data['maneuver'], 'String');
            }
            if (data.hasOwnProperty('html_instructions')) {
                obj['html_instructions'] = ApiClient.convertToType(data['html_instructions'], 'String');
            }
            if (data.hasOwnProperty('distance')) {
                obj['distance'] = ApiClient.convertToType(data['distance'], 'Number');
            }
            if (data.hasOwnProperty('duration')) {
                obj['duration'] = ApiClient.convertToType(data['duration'], 'Number');
            }
            if (data.hasOwnProperty('note')) {
                obj['note'] = ApiClient.convertToType(data['note'], ['String']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/DirectionPosition} position
    */
    'position' = undefined;
    /**
    * @member {String} maneuver
    */
    'maneuver' = undefined;
    /**
    * @member {String} html_instructions
    */
    'html_instructions' = undefined;
    /**
    * @member {Number} distance
    */
    'distance' = undefined;
    /**
    * @member {Number} duration
    */
    'duration' = undefined;
    /**
    * @member {Array.<String>} note
    */
    'note' = undefined;




}
