/**
 * TollGuru Calculator
 * TollGuru Calculator API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 2020-05-31T17:48:12Z
 * Contact: eng@tollguru.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The DirectionPosition model module.
* @module model/DirectionPosition
* @version 2020-05-31T17:48:12Z
*/
export default class DirectionPosition {
    /**
    * Constructs a new <code>DirectionPosition</code>.
    * @alias module:model/DirectionPosition
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>DirectionPosition</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/DirectionPosition} obj Optional instance to populate.
    * @return {module:model/DirectionPosition} The populated <code>DirectionPosition</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DirectionPosition();
                        
            
            if (data.hasOwnProperty('latitude')) {
                obj['latitude'] = ApiClient.convertToType(data['latitude'], 'Number');
            }
            if (data.hasOwnProperty('longitude')) {
                obj['longitude'] = ApiClient.convertToType(data['longitude'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Number} latitude
    */
    'latitude' = undefined;
    /**
    * @member {Number} longitude
    */
    'longitude' = undefined;




}
