/**
 * TollGuru Calculator
 * TollGuru Calculator API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 2020-05-31T17:48:12Z
 * Contact: eng@tollguru.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The FuelEfficiency model module.
* @module model/FuelEfficiency
* @version 2020-05-31T17:48:12Z
*/
export default class FuelEfficiency {
    /**
    * Constructs a new <code>FuelEfficiency</code>.
    * If you want an accurate estimate of fuel expenses, you will need to specify parameters specific to fuel price and fuel efficiency as fuelEfficiency object.
    * @alias module:model/FuelEfficiency
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>FuelEfficiency</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/FuelEfficiency} obj Optional instance to populate.
    * @return {module:model/FuelEfficiency} The populated <code>FuelEfficiency</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FuelEfficiency();
                        
            
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'Number');
            }
            if (data.hasOwnProperty('hwy')) {
                obj['hwy'] = ApiClient.convertToType(data['hwy'], 'Number');
            }
            if (data.hasOwnProperty('units')) {
                obj['units'] = ApiClient.convertToType(data['units'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} city
    * @default 23.4
    */
    'city' = 23.4;
    /**
    * @member {Number} hwy
    * @default 29.25
    */
    'hwy' = 29.25;
    /**
    * @member {module:model/FuelEfficiency.UnitsEnum} units
    * @default 'mpg'
    */
    'units' = 'mpg';



    /**
    * Allowed values for the <code>units</code> property.
    * @enum {String}
    * @readonly
    */
    static UnitsEnum = {
        /**
         * value: "mpg"
         * @const
         */
        "mpg": "mpg",
        /**
         * value: "kmpl"
         * @const
         */
        "kmpl": "kmpl",
        /**
         * value: "l100"
         * @const
         */
        "l100": "l100"    };

}
