/**
 * TollGuru Calculator
 * TollGuru Calculator API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 2020-05-31T17:48:12Z
 * Contact: eng@tollguru.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The GeoCordinates model module.
* @module model/GeoCordinates
* @version 2020-05-31T17:48:12Z
*/
export default class GeoCordinates {
    /**
    * Constructs a new <code>GeoCordinates</code>.
    * geo-coordinates
    * @alias module:model/GeoCordinates
    * @class
    */

    constructor() {
        
        OneOfLocation.call(this);
        
    }

    /**
    * Constructs a <code>GeoCordinates</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/GeoCordinates} obj Optional instance to populate.
    * @return {module:model/GeoCordinates} The populated <code>GeoCordinates</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GeoCordinates();
                        
            
            if (data.hasOwnProperty('lat')) {
                obj['lat'] = ApiClient.convertToType(data['lat'], 'Number');
            }
            if (data.hasOwnProperty('lng')) {
                obj['lng'] = ApiClient.convertToType(data['lng'], 'Number');
            }
        }
        return obj;
    }

    /**
    * Specify as geo-coordinates (latitude)
    * @member {Number} lat
    */
    'lat' = undefined;
    /**
    * Specify as geo-coordinates (longitude)
    * @member {Number} lng
    */
    'lng' = undefined;

    // Implement OneOfLocation interface:
    


}
