/**
 * TollGuru Calculator
 * TollGuru Calculator API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 2020-05-31T17:48:12Z
 * Contact: eng@tollguru.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Cost from './Cost';
import Direction from './Direction';
import HosResponse from './HosResponse';
import RouteResponseSummary from './RouteResponseSummary';
import Toll from './Toll';

/**
* The GmapRouteResponse model module.
* @module model/GmapRouteResponse
* @version 2020-05-31T17:48:12Z
*/
export default class GmapRouteResponse {
    /**
    * Constructs a new <code>GmapRouteResponse</code>.
    * @alias module:model/GmapRouteResponse
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>GmapRouteResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/GmapRouteResponse} obj Optional instance to populate.
    * @return {module:model/GmapRouteResponse} The populated <code>GmapRouteResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GmapRouteResponse();
                        
            
            if (data.hasOwnProperty('summary')) {
                obj['summary'] = RouteResponseSummary.constructFromObject(data['summary']);
            }
            if (data.hasOwnProperty('costs')) {
                obj['costs'] = Cost.constructFromObject(data['costs']);
            }
            if (data.hasOwnProperty('tolls')) {
                obj['tolls'] = ApiClient.convertToType(data['tolls'], [Toll]);
            }
            if (data.hasOwnProperty('directions')) {
                obj['directions'] = ApiClient.convertToType(data['directions'], [Direction]);
            }
            if (data.hasOwnProperty('herePath')) {
                obj['herePath'] = ApiClient.convertToType(data['herePath'], ['Number']);
            }
            if (data.hasOwnProperty('hos')) {
                obj['hos'] = HosResponse.constructFromObject(data['hos']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/RouteResponseSummary} summary
    */
    'summary' = undefined;
    /**
    * @member {module:model/Cost} costs
    */
    'costs' = undefined;
    /**
    * @member {Array.<module:model/Toll>} tolls
    */
    'tolls' = undefined;
    /**
    * @member {Array.<module:model/Direction>} directions
    */
    'directions' = undefined;
    /**
    * @member {Array.<Number>} herePath
    */
    'herePath' = undefined;
    /**
    * @member {module:model/HosResponse} hos
    */
    'hos' = undefined;




}
