/**
 * TollGuru Calculator
 * TollGuru Calculator API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 2020-05-31T17:48:12Z
 * Contact: eng@tollguru.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import HosResponseSummaryTotalDistance from './HosResponseSummaryTotalDistance';
import HosResponseSummaryTotalDriveDuration from './HosResponseSummaryTotalDriveDuration';

/**
* The HosData model module.
* @module model/HosData
* @version 2020-05-31T17:48:12Z
*/
export default class HosData {
    /**
    * Constructs a new <code>HosData</code>.
    * @alias module:model/HosData
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>HosData</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/HosData} obj Optional instance to populate.
    * @return {module:model/HosData} The populated <code>HosData</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HosData();
                        
            
            if (data.hasOwnProperty('instruction')) {
                obj['instruction'] = ApiClient.convertToType(data['instruction'], 'String');
            }
            if (data.hasOwnProperty('duration')) {
                obj['duration'] = HosResponseSummaryTotalDriveDuration.constructFromObject(data['duration']);
            }
            if (data.hasOwnProperty('distance')) {
                obj['distance'] = HosResponseSummaryTotalDistance.constructFromObject(data['distance']);
            }
        }
        return obj;
    }

    /**
    * @member {String} instruction
    */
    'instruction' = undefined;
    /**
    * @member {module:model/HosResponseSummaryTotalDriveDuration} duration
    */
    'duration' = undefined;
    /**
    * @member {module:model/HosResponseSummaryTotalDistance} distance
    */
    'distance' = undefined;




}
