/**
 * TollGuru Calculator
 * TollGuru Calculator API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 2020-05-31T17:48:12Z
 * Contact: eng@tollguru.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import HosData from './HosData';
import HosResponseSummary from './HosResponseSummary';
import Stop from './Stop';

/**
* The HosResponse model module.
* @module model/HosResponse
* @version 2020-05-31T17:48:12Z
*/
export default class HosResponse {
    /**
    * Constructs a new <code>HosResponse</code>.
    * @alias module:model/HosResponse
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>HosResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/HosResponse} obj Optional instance to populate.
    * @return {module:model/HosResponse} The populated <code>HosResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HosResponse();
                        
            
            if (data.hasOwnProperty('summary')) {
                obj['summary'] = HosResponseSummary.constructFromObject(data['summary']);
            }
            if (data.hasOwnProperty('break_points')) {
                obj['break_points'] = ApiClient.convertToType(data['break_points'], [['String']]);
            }
            if (data.hasOwnProperty('stops')) {
                obj['stops'] = ApiClient.convertToType(data['stops'], [Stop]);
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [HosData]);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/HosResponseSummary} summary
    */
    'summary' = undefined;
    /**
    * @member {Array.<Array.<String>>} break_points
    */
    'break_points' = undefined;
    /**
    * @member {Array.<module:model/Stop>} stops
    */
    'stops' = undefined;
    /**
    * @member {Array.<module:model/HosData>} data
    */
    'data' = undefined;




}
