/**
 * TollGuru Calculator
 * TollGuru Calculator API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 2020-05-31T17:48:12Z
 * Contact: eng@tollguru.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import HosResponseSummaryTotalDistance from './HosResponseSummaryTotalDistance';
import HosResponseSummaryTotalDriveDuration from './HosResponseSummaryTotalDriveDuration';

/**
* The HosResponseSummary model module.
* @module model/HosResponseSummary
* @version 2020-05-31T17:48:12Z
*/
export default class HosResponseSummary {
    /**
    * Constructs a new <code>HosResponseSummary</code>.
    * @alias module:model/HosResponseSummary
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>HosResponseSummary</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/HosResponseSummary} obj Optional instance to populate.
    * @return {module:model/HosResponseSummary} The populated <code>HosResponseSummary</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HosResponseSummary();
                        
            
            if (data.hasOwnProperty('total_drive_duration')) {
                obj['total_drive_duration'] = HosResponseSummaryTotalDriveDuration.constructFromObject(data['total_drive_duration']);
            }
            if (data.hasOwnProperty('total_break_duration')) {
                obj['total_break_duration'] = HosResponseSummaryTotalDriveDuration.constructFromObject(data['total_break_duration']);
            }
            if (data.hasOwnProperty('total_duration')) {
                obj['total_duration'] = HosResponseSummaryTotalDriveDuration.constructFromObject(data['total_duration']);
            }
            if (data.hasOwnProperty('total_distance')) {
                obj['total_distance'] = HosResponseSummaryTotalDistance.constructFromObject(data['total_distance']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/HosResponseSummaryTotalDriveDuration} total_drive_duration
    */
    'total_drive_duration' = undefined;
    /**
    * @member {module:model/HosResponseSummaryTotalDriveDuration} total_break_duration
    */
    'total_break_duration' = undefined;
    /**
    * @member {module:model/HosResponseSummaryTotalDriveDuration} total_duration
    */
    'total_duration' = undefined;
    /**
    * @member {module:model/HosResponseSummaryTotalDistance} total_distance
    */
    'total_distance' = undefined;




}
