/**
 * TollGuru Calculator
 * TollGuru Calculator API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 2020-05-31T17:48:12Z
 * Contact: eng@tollguru.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The HosReq model module.
* @module model/HosReq
* @version 2020-05-31T17:48:12Z
*/
export default class HosReq {
    /**
    * Constructs a new <code>HosReq</code>.
    * @alias module:model/HosReq
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>HosReq</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/HosReq} obj Optional instance to populate.
    * @return {module:model/HosReq} The populated <code>HosReq</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HosReq();
                        
            
            if (data.hasOwnProperty('rule')) {
                obj['rule'] = ApiClient.convertToType(data['rule'], 'String');
            }
            if (data.hasOwnProperty('dutyHoursBeforeEndOfWorkDay')) {
                obj['dutyHoursBeforeEndOfWorkDay'] = ApiClient.convertToType(data['dutyHoursBeforeEndOfWorkDay'], 'Number');
            }
            if (data.hasOwnProperty('dutyHoursBeforeRestBreak')) {
                obj['dutyHoursBeforeRestBreak'] = ApiClient.convertToType(data['dutyHoursBeforeRestBreak'], 'Number');
            }
            if (data.hasOwnProperty('drivingHoursBeforeEndOfWorkDay')) {
                obj['drivingHoursBeforeEndOfWorkDay'] = ApiClient.convertToType(data['drivingHoursBeforeEndOfWorkDay'], 'Number');
            }
            if (data.hasOwnProperty('timeRemaining')) {
                obj['timeRemaining'] = ApiClient.convertToType(data['timeRemaining'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/HosReq.RuleEnum} rule
    */
    'rule' = undefined;
    /**
    * @member {Number} dutyHoursBeforeEndOfWorkDay
    */
    'dutyHoursBeforeEndOfWorkDay' = undefined;
    /**
    * @member {Number} dutyHoursBeforeRestBreak
    */
    'dutyHoursBeforeRestBreak' = undefined;
    /**
    * @member {Number} drivingHoursBeforeEndOfWorkDay
    */
    'drivingHoursBeforeEndOfWorkDay' = undefined;
    /**
    * @member {Number} timeRemaining
    */
    'timeRemaining' = undefined;



    /**
    * Allowed values for the <code>rule</code> property.
    * @enum {String}
    * @readonly
    */
    static RuleEnum = {
        /**
         * value: "60"
         * @const
         */
        "60": "60",
        /**
         * value: "70"
         * @const
         */
        "70": "70"    };

}
