/**
 * TollGuru Calculator
 * TollGuru Calculator API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 2020-05-31T17:48:12Z
 * Contact: eng@tollguru.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Cost from './Cost';
import Toll from './Toll';

/**
* The InlineResponse200Route model module.
* @module model/InlineResponse200Route
* @version 2020-05-31T17:48:12Z
*/
export default class InlineResponse200Route {
    /**
    * Constructs a new <code>InlineResponse200Route</code>.
    * Route information including tolls
    * @alias module:model/InlineResponse200Route
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>InlineResponse200Route</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse200Route} obj Optional instance to populate.
    * @return {module:model/InlineResponse200Route} The populated <code>InlineResponse200Route</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse200Route();
                        
            
            if (data.hasOwnProperty('hasTolls')) {
                obj['hasTolls'] = ApiClient.convertToType(data['hasTolls'], 'Boolean');
            }
            if (data.hasOwnProperty('costs')) {
                obj['costs'] = Cost.constructFromObject(data['costs']);
            }
            if (data.hasOwnProperty('tolls')) {
                obj['tolls'] = ApiClient.convertToType(data['tolls'], [Toll]);
            }
        }
        return obj;
    }

    /**
    * @member {Boolean} hasTolls
    */
    'hasTolls' = undefined;
    /**
    * @member {module:model/Cost} costs
    */
    'costs' = undefined;
    /**
    * @member {Array.<module:model/Toll>} tolls
    */
    'tolls' = undefined;




}
