/**
 * TollGuru Calculator
 * TollGuru Calculator API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 2020-05-31T17:48:12Z
 * Contact: eng@tollguru.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The OneOfLocation model module.
* @module model/OneOfLocation
* @version 2020-05-31T17:48:12Z
*/
export default class OneOfLocation {
    /**
    * Constructs a new <code>OneOfLocation</code>.
    * @alias module:model/OneOfLocation
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>OneOfLocation</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/OneOfLocation} obj Optional instance to populate.
    * @return {module:model/OneOfLocation} The populated <code>OneOfLocation</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OneOfLocation();
                        
            
        }
        return obj;
    }





}
