/**
 * TollGuru Calculator
 * TollGuru Calculator API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 2020-05-31T17:48:12Z
 * Contact: eng@tollguru.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The PlaceId model module.
* @module model/PlaceId
* @version 2020-05-31T17:48:12Z
*/
export default class PlaceId {
    /**
    * Constructs a new <code>PlaceId</code>.
    * @alias module:model/PlaceId
    * @class
    */

    constructor() {
        
        OneOfLocation.call(this);
        
    }

    /**
    * Constructs a <code>PlaceId</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PlaceId} obj Optional instance to populate.
    * @return {module:model/PlaceId} The populated <code>PlaceId</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PlaceId();
                        
            
            if (data.hasOwnProperty('place_id')) {
                obj['place_id'] = ApiClient.convertToType(data['place_id'], 'String');
            }
        }
        return obj;
    }

    /**
    * Specify as Google Place ID string, such as ChIJlTlXssSPxokROy60gaOlloQ
    * @member {String} place_id
    */
    'place_id' = undefined;

    // Implement OneOfLocation interface:
    


}
