/**
 * TollGuru Calculator
 * TollGuru Calculator API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 2020-05-31T17:48:12Z
 * Contact: eng@tollguru.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Rates model module.
* @module model/Rates
* @version 2020-05-31T17:48:12Z
*/
export default class Rates {
    /**
    * Constructs a new <code>Rates</code>.
    * Rates object that specifies conversion factors between currencies with US Dollar as base. It is useful when you are looking for tolls between countries. Say you are looking for tolls between Toronto, Canada, and Monterrey, Mexico. Some of the tolls are in Canadian dollars, some in USD and others in Mexican Pesos. The total costs are specified in one currency using the conversion factors. The conversion factors are based on dynamic exchange rates.
    * @alias module:model/Rates
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Rates</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Rates} obj Optional instance to populate.
    * @return {module:model/Rates} The populated <code>Rates</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Rates();
                        
            
        }
        return obj;
    }





}
