/**
 * TollGuru Calculator
 * TollGuru Calculator API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 2020-05-31T17:48:12Z
 * Contact: eng@tollguru.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The RouteResponseSummaryDiffs model module.
* @module model/RouteResponseSummaryDiffs
* @version 2020-05-31T17:48:12Z
*/
export default class RouteResponseSummaryDiffs {
    /**
    * Constructs a new <code>RouteResponseSummaryDiffs</code>.
    * @alias module:model/RouteResponseSummaryDiffs
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>RouteResponseSummaryDiffs</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/RouteResponseSummaryDiffs} obj Optional instance to populate.
    * @return {module:model/RouteResponseSummaryDiffs} The populated <code>RouteResponseSummaryDiffs</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RouteResponseSummaryDiffs();
                        
            
            if (data.hasOwnProperty('cheapest')) {
                obj['cheapest'] = ApiClient.convertToType(data['cheapest'], 'Number');
            }
            if (data.hasOwnProperty('fastest')) {
                obj['fastest'] = ApiClient.convertToType(data['fastest'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Number} cheapest
    */
    'cheapest' = undefined;
    /**
    * @member {Number} fastest
    */
    'fastest' = undefined;




}
