/**
 * TollGuru Calculator
 * TollGuru Calculator API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 2020-05-31T17:48:12Z
 * Contact: eng@tollguru.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RouteLocation from './RouteLocation';

/**
* The Route model module.
* @module model/Route
* @version 2020-05-31T17:48:12Z
*/
export default class Route {
    /**
    * Constructs a new <code>Route</code>.
    * @alias module:model/Route
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Route</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Route} obj Optional instance to populate.
    * @return {module:model/Route} The populated <code>Route</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Route();
                        
            
            if (data.hasOwnProperty('location')) {
                obj['location'] = RouteLocation.constructFromObject(data['location']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/RouteLocation} location
    */
    'location' = undefined;




}
