/**
 * TollGuru Calculator
 * TollGuru Calculator API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 2020-05-31T17:48:12Z
 * Contact: eng@tollguru.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Rates from './Rates';

/**
* The SyncResponseSummary model module.
* @module model/SyncResponseSummary
* @version 2020-05-31T17:48:12Z
*/
export default class SyncResponseSummary {
    /**
    * Constructs a new <code>SyncResponseSummary</code>.
    * @alias module:model/SyncResponseSummary
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>SyncResponseSummary</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SyncResponseSummary} obj Optional instance to populate.
    * @return {module:model/SyncResponseSummary} The populated <code>SyncResponseSummary</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SyncResponseSummary();
                        
            
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('rates')) {
                obj['rates'] = Rates.constructFromObject(data['rates']);
            }
            if (data.hasOwnProperty('departure_time')) {
                obj['departure_time'] = ApiClient.convertToType(data['departure_time'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {String} status
    */
    'status' = undefined;
    /**
    * @member {module:model/Rates} rates
    */
    'rates' = undefined;
    /**
    * @member {Number} departure_time
    */
    'departure_time' = undefined;




}
