/**
 * TollGuru Calculator
 * TollGuru Calculator API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 2020-05-31T17:48:12Z
 * Contact: eng@tollguru.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TeritoryMielageResInner from './TeritoryMielageResInner';

/**
* The TeritoryMielageRes model module.
* @module model/TeritoryMielageRes
* @version 2020-05-31T17:48:12Z
*/
export default class TeritoryMielageRes extends Array {
    /**
    * Constructs a new <code>TeritoryMielageRes</code>.
    * @alias module:model/TeritoryMielageRes
    * @class
    * @extends Array
    */

    constructor() {
        super();
        
        
        return this;
    }

    /**
    * Constructs a <code>TeritoryMielageRes</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TeritoryMielageRes} obj Optional instance to populate.
    * @return {module:model/TeritoryMielageRes} The populated <code>TeritoryMielageRes</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TeritoryMielageRes();
            ApiClient.constructFromObject(data, obj, 'TeritoryMielageResInner');
            
            
        }
        return obj;
    }





}
