/**
 * TollGuru Calculator
 * TollGuru Calculator API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 2020-05-31T17:48:12Z
 * Contact: eng@tollguru.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The TeritoryMielageResInner model module.
* @module model/TeritoryMielageResInner
* @version 2020-05-31T17:48:12Z
*/
export default class TeritoryMielageResInner {
    /**
    * Constructs a new <code>TeritoryMielageResInner</code>.
    * @alias module:model/TeritoryMielageResInner
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>TeritoryMielageResInner</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TeritoryMielageResInner} obj Optional instance to populate.
    * @return {module:model/TeritoryMielageResInner} The populated <code>TeritoryMielageResInner</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TeritoryMielageResInner();
                        
            
            if (data.hasOwnProperty('territory')) {
                obj['territory'] = ApiClient.convertToType(data['territory'], Object);
            }
            if (data.hasOwnProperty('distance')) {
                obj['distance'] = ApiClient.convertToType(data['distance'], Object);
            }
            if (data.hasOwnProperty('trafficTime')) {
                obj['trafficTime'] = ApiClient.convertToType(data['trafficTime'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Object} territory
    */
    'territory' = undefined;
    /**
    * @member {Object} distance
    */
    'distance' = undefined;
    /**
    * @member {String} trafficTime
    */
    'trafficTime' = undefined;




}
