/**
 * TollGuru Calculator
 * TollGuru Calculator API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 2020-05-31T17:48:12Z
 * Contact: eng@tollguru.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class VehicleType.
* @enum {}
* @readonly
*/
export default class VehicleType {
        /**
         * value: "2AxlesAuto"
         * @const
         */
        2AxlesAuto = "2AxlesAuto";

        /**
         * value: "3AxlesAuto"
         * @const
         */
        3AxlesAuto = "3AxlesAuto";

        /**
         * value: "4AxlesAuto"
         * @const
         */
        4AxlesAuto = "4AxlesAuto";

        /**
         * value: "2AxlesDualTire"
         * @const
         */
        2AxlesDualTire = "2AxlesDualTire";

        /**
         * value: "3AxlesDualTire"
         * @const
         */
        3AxlesDualTire = "3AxlesDualTire";

        /**
         * value: "4AxlesDualTire"
         * @const
         */
        4AxlesDualTire = "4AxlesDualTire";

        /**
         * value: "2AxlesTruck"
         * @const
         */
        2AxlesTruck = "2AxlesTruck";

        /**
         * value: "3AxlesTruck"
         * @const
         */
        3AxlesTruck = "3AxlesTruck";

        /**
         * value: "4AxlesTruck"
         * @const
         */
        4AxlesTruck = "4AxlesTruck";

        /**
         * value: "5AxlesTruck"
         * @const
         */
        5AxlesTruck = "5AxlesTruck";

        /**
         * value: "6AxlesTruck"
         * @const
         */
        6AxlesTruck = "6AxlesTruck";

        /**
         * value: "7AxlesTruck"
         * @const
         */
        7AxlesTruck = "7AxlesTruck";

        /**
         * value: "8AxlesTruck"
         * @const
         */
        8AxlesTruck = "8AxlesTruck";

        /**
         * value: "9AxlesTruck"
         * @const
         */
        9AxlesTruck = "9AxlesTruck";

        /**
         * value: "2AxlesBus"
         * @const
         */
        2AxlesBus = "2AxlesBus";

        /**
         * value: "3AxlesBus"
         * @const
         */
        3AxlesBus = "3AxlesBus";

        /**
         * value: "2AxlesMotorcycle"
         * @const
         */
        2AxlesMotorcycle = "2AxlesMotorcycle";

        /**
         * value: "3AxlesMotorcycle"
         * @const
         */
        3AxlesMotorcycle = "3AxlesMotorcycle";

        /**
         * value: "2AxlesRv"
         * @const
         */
        2AxlesRv = "2AxlesRv";

        /**
         * value: "3AxlesRv"
         * @const
         */
        3AxlesRv = "3AxlesRv";

        /**
         * value: "4AxlesRv"
         * @const
         */
        4AxlesRv = "4AxlesRv";


    /**
    * Returns a <code>VehicleType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/VehicleType} The enum <code>VehicleType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}
