/**
 * TollGuru Calculator
 * TollGuru Calculator API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 2020-05-31T17:48:12Z
 * Contact: eng@tollguru.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TollGuruCalculator);
  }
}(this, function(expect, TollGuruCalculator) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TollGuruCalculator.Cost();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Cost', function() {
    it('should create an instance of Cost', function() {
      // uncomment below and update the code to test Cost
      //var instane = new TollGuruCalculator.Cost();
      //expect(instance).to.be.a(TollGuruCalculator.Cost);
    });

    it('should have the property fuel (base name: "fuel")', function() {
      // uncomment below and update the code to test the property fuel
      //var instane = new TollGuruCalculator.Cost();
      //expect(instance).to.be();
    });

    it('should have the property otherCost (base name: "otherCost")', function() {
      // uncomment below and update the code to test the property otherCost
      //var instane = new TollGuruCalculator.Cost();
      //expect(instance).to.be();
    });

    it('should have the property tag (base name: "tag")', function() {
      // uncomment below and update the code to test the property tag
      //var instane = new TollGuruCalculator.Cost();
      //expect(instance).to.be();
    });

    it('should have the property cash (base name: "cash")', function() {
      // uncomment below and update the code to test the property cash
      //var instane = new TollGuruCalculator.Cost();
      //expect(instance).to.be();
    });

    it('should have the property licensePlate (base name: "licensePlate")', function() {
      // uncomment below and update the code to test the property licensePlate
      //var instane = new TollGuruCalculator.Cost();
      //expect(instance).to.be();
    });

    it('should have the property creditCard (base name: "creditCard")', function() {
      // uncomment below and update the code to test the property creditCard
      //var instane = new TollGuruCalculator.Cost();
      //expect(instance).to.be();
    });

    it('should have the property prepaidCard (base name: "prepaidCard")', function() {
      // uncomment below and update the code to test the property prepaidCard
      //var instane = new TollGuruCalculator.Cost();
      //expect(instance).to.be();
    });

  });

}));
