/**
 * TollGuru Calculator
 * TollGuru Calculator API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 2020-05-31T17:48:12Z
 * Contact: eng@tollguru.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TollGuruCalculator);
  }
}(this, function(expect, TollGuruCalculator) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TollGuruCalculator.Stop();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Stop', function() {
    it('should create an instance of Stop', function() {
      // uncomment below and update the code to test Stop
      //var instane = new TollGuruCalculator.Stop();
      //expect(instance).to.be.a(TollGuruCalculator.Stop);
    });

    it('should have the property additionalServices (base name: "additionalServices")', function() {
      // uncomment below and update the code to test the property additionalServices
      //var instane = new TollGuruCalculator.Stop();
      //expect(instance).to.be();
    });

    it('should have the property amenities (base name: "amenities")', function() {
      // uncomment below and update the code to test the property amenities
      //var instane = new TollGuruCalculator.Stop();
      //expect(instance).to.be();
    });

    it('should have the property businessesName (base name: "businessesName")', function() {
      // uncomment below and update the code to test the property businessesName
      //var instane = new TollGuruCalculator.Stop();
      //expect(instance).to.be();
    });

    it('should have the property city (base name: "city")', function() {
      // uncomment below and update the code to test the property city
      //var instane = new TollGuruCalculator.Stop();
      //expect(instance).to.be();
    });

    it('should have the property contactName (base name: "contactName")', function() {
      // uncomment below and update the code to test the property contactName
      //var instane = new TollGuruCalculator.Stop();
      //expect(instance).to.be();
    });

    it('should have the property fax (base name: "fax")', function() {
      // uncomment below and update the code to test the property fax
      //var instane = new TollGuruCalculator.Stop();
      //expect(instance).to.be();
    });

    it('should have the property fuelLanes (base name: "fuelLanes")', function() {
      // uncomment below and update the code to test the property fuelLanes
      //var instane = new TollGuruCalculator.Stop();
      //expect(instance).to.be();
    });

    it('should have the property highway (base name: "highway")', function() {
      // uncomment below and update the code to test the property highway
      //var instane = new TollGuruCalculator.Stop();
      //expect(instance).to.be();
    });

    it('should have the property latitude (base name: "latitude")', function() {
      // uncomment below and update the code to test the property latitude
      //var instane = new TollGuruCalculator.Stop();
      //expect(instance).to.be();
    });

    it('should have the property longitude (base name: "longitude")', function() {
      // uncomment below and update the code to test the property longitude
      //var instane = new TollGuruCalculator.Stop();
      //expect(instance).to.be();
    });

    it('should have the property parkingSpots (base name: "parkingSpots")', function() {
      // uncomment below and update the code to test the property parkingSpots
      //var instane = new TollGuruCalculator.Stop();
      //expect(instance).to.be();
    });

    it('should have the property paymentMethods (base name: "paymentMethods")', function() {
      // uncomment below and update the code to test the property paymentMethods
      //var instane = new TollGuruCalculator.Stop();
      //expect(instance).to.be();
    });

    it('should have the property phone1 (base name: "phone1")', function() {
      // uncomment below and update the code to test the property phone1
      //var instane = new TollGuruCalculator.Stop();
      //expect(instance).to.be();
    });

    it('should have the property phone2 (base name: "phone2")', function() {
      // uncomment below and update the code to test the property phone2
      //var instane = new TollGuruCalculator.Stop();
      //expect(instance).to.be();
    });

    it('should have the property phone3 (base name: "phone3")', function() {
      // uncomment below and update the code to test the property phone3
      //var instane = new TollGuruCalculator.Stop();
      //expect(instance).to.be();
    });

    it('should have the property postalCode (base name: "postalCode")', function() {
      // uncomment below and update the code to test the property postalCode
      //var instane = new TollGuruCalculator.Stop();
      //expect(instance).to.be();
    });

    it('should have the property restIndex (base name: "restIndex")', function() {
      // uncomment below and update the code to test the property restIndex
      //var instane = new TollGuruCalculator.Stop();
      //expect(instance).to.be();
    });

    it('should have the property showers (base name: "showers")', function() {
      // uncomment below and update the code to test the property showers
      //var instane = new TollGuruCalculator.Stop();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instane = new TollGuruCalculator.Stop();
      //expect(instance).to.be();
    });

    it('should have the property stopId (base name: "stopId")', function() {
      // uncomment below and update the code to test the property stopId
      //var instane = new TollGuruCalculator.Stop();
      //expect(instance).to.be();
    });

    it('should have the property streetAddress (base name: "streetAddress")', function() {
      // uncomment below and update the code to test the property streetAddress
      //var instane = new TollGuruCalculator.Stop();
      //expect(instance).to.be();
    });

    it('should have the property truckServiceBays (base name: "truckServiceBays")', function() {
      // uncomment below and update the code to test the property truckServiceBays
      //var instane = new TollGuruCalculator.Stop();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new TollGuruCalculator.Stop();
      //expect(instance).to.be();
    });

    it('should have the property webAddress (base name: "webAddress")', function() {
      // uncomment below and update the code to test the property webAddress
      //var instane = new TollGuruCalculator.Stop();
      //expect(instance).to.be();
    });

  });

}));
