/**
 * TollGuru Calculator
 * TollGuru Calculator API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 2020-05-31T17:48:12Z
 * Contact: eng@tollguru.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from './ApiClient';
import Address from './model/Address';
import AllOfGmapRequestBodyDriver from './model/AllOfGmapRequestBodyDriver';
import AllOfGmapRequestBodyFrom from './model/AllOfGmapRequestBodyFrom';
import AllOfGmapRequestBodyFuelEfficiency from './model/AllOfGmapRequestBodyFuelEfficiency';
import AllOfGmapRequestBodyHos from './model/AllOfGmapRequestBodyHos';
import AllOfGmapRequestBodyTo from './model/AllOfGmapRequestBodyTo';
import AllOfGmapRequestBodyVehicleType from './model/AllOfGmapRequestBodyVehicleType';
import AllOfHereRequestBodyDriver from './model/AllOfHereRequestBodyDriver';
import AllOfHereRequestBodyFrom from './model/AllOfHereRequestBodyFrom';
import AllOfHereRequestBodyFuelEfficiency from './model/AllOfHereRequestBodyFuelEfficiency';
import AllOfHereRequestBodyHos from './model/AllOfHereRequestBodyHos';
import AllOfHereRequestBodyTo from './model/AllOfHereRequestBodyTo';
import AllOfHereRequestBodyTruck from './model/AllOfHereRequestBodyTruck';
import AllOfHereRequestBodyVehicleType from './model/AllOfHereRequestBodyVehicleType';
import AllOfHereResponseSummaryFuelEfficiency from './model/AllOfHereResponseSummaryFuelEfficiency';
import AllOfHereResponseSummaryVehicleType from './model/AllOfHereResponseSummaryVehicleType';
import AnyOfbody from './model/AnyOfbody';
import AsyncResponse from './model/AsyncResponse';
import Body from './model/Body';
import Body1 from './model/Body1';
import Cost from './model/Cost';
import DateTime from './model/DateTime';
import Direction from './model/Direction';
import DirectionPosition from './model/DirectionPosition';
import Driver from './model/Driver';
import FuelEfficiency from './model/FuelEfficiency';
import GeoCordinates from './model/GeoCordinates';
import GmapRequestBody from './model/GmapRequestBody';
import GmapResponse from './model/GmapResponse';
import GmapRouteResponse from './model/GmapRouteResponse';
import HereRequestBody from './model/HereRequestBody';
import HereResponse from './model/HereResponse';
import HereResponseSummary from './model/HereResponseSummary';
import HereResponseSummaryFuelPrice from './model/HereResponseSummaryFuelPrice';
import HosData from './model/HosData';
import HosReq from './model/HosReq';
import HosResponse from './model/HosResponse';
import HosResponseSummary from './model/HosResponseSummary';
import HosResponseSummaryTotalDistance from './model/HosResponseSummaryTotalDistance';
import HosResponseSummaryTotalDriveDuration from './model/HosResponseSummaryTotalDriveDuration';
import InlineResponse200 from './model/InlineResponse200';
import InlineResponse2001 from './model/InlineResponse2001';
import InlineResponse200Route from './model/InlineResponse200Route';
import Location from './model/Location';
import OneOfGmapRequestBodyDepartureTime from './model/OneOfGmapRequestBodyDepartureTime';
import OneOfHereRequestBodyDepartureTime from './model/OneOfHereRequestBodyDepartureTime';
import OneOfLocation from './model/OneOfLocation';
import OneOfinlineResponse2001 from './model/OneOfinlineResponse2001';
import PlaceId from './model/PlaceId';
import Rates from './model/Rates';
import Route from './model/Route';
import RouteLocation from './model/RouteLocation';
import RouteResponse from './model/RouteResponse';
import RouteResponseSummary from './model/RouteResponseSummary';
import RouteResponseSummaryDiffs from './model/RouteResponseSummaryDiffs';
import RouteResponseSummaryDistance from './model/RouteResponseSummaryDistance';
import RouteResponseSummaryDuration from './model/RouteResponseSummaryDuration';
import Stop from './model/Stop';
import SyncResponse from './model/SyncResponse';
import SyncResponseRoute from './model/SyncResponseRoute';
import SyncResponseSummary from './model/SyncResponseSummary';
import TeritoryMielageRes from './model/TeritoryMielageRes';
import TeritoryMielageResInner from './model/TeritoryMielageResInner';
import Timestamp from './model/Timestamp';
import Toll from './model/Toll';
import Truck from './model/Truck';
import VehicleType from './model/VehicleType';
import GPSTracestracksApi from './api/GPSTracestracksApi';
import OriginAndDestinationPairApi from './api/OriginAndDestinationPairApi';
import RoutePolylineApi from './api/RoutePolylineApi';

/**
* TollGuru_Calculator_API_Authentication___ReDoc_Inject_security_definitions___.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var TollGuruCalculator = require('index'); // See note below*.
* var xxxSvc = new TollGuruCalculator.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new TollGuruCalculator.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new TollGuruCalculator.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new TollGuruCalculator.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 2020-05-31T17:48:12Z
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Address model constructor.
     * @property {module:model/Address}
     */
    Address,

    /**
     * The AllOfGmapRequestBodyDriver model constructor.
     * @property {module:model/AllOfGmapRequestBodyDriver}
     */
    AllOfGmapRequestBodyDriver,

    /**
     * The AllOfGmapRequestBodyFrom model constructor.
     * @property {module:model/AllOfGmapRequestBodyFrom}
     */
    AllOfGmapRequestBodyFrom,

    /**
     * The AllOfGmapRequestBodyFuelEfficiency model constructor.
     * @property {module:model/AllOfGmapRequestBodyFuelEfficiency}
     */
    AllOfGmapRequestBodyFuelEfficiency,

    /**
     * The AllOfGmapRequestBodyHos model constructor.
     * @property {module:model/AllOfGmapRequestBodyHos}
     */
    AllOfGmapRequestBodyHos,

    /**
     * The AllOfGmapRequestBodyTo model constructor.
     * @property {module:model/AllOfGmapRequestBodyTo}
     */
    AllOfGmapRequestBodyTo,

    /**
     * The AllOfGmapRequestBodyVehicleType model constructor.
     * @property {module:model/AllOfGmapRequestBodyVehicleType}
     */
    AllOfGmapRequestBodyVehicleType,

    /**
     * The AllOfHereRequestBodyDriver model constructor.
     * @property {module:model/AllOfHereRequestBodyDriver}
     */
    AllOfHereRequestBodyDriver,

    /**
     * The AllOfHereRequestBodyFrom model constructor.
     * @property {module:model/AllOfHereRequestBodyFrom}
     */
    AllOfHereRequestBodyFrom,

    /**
     * The AllOfHereRequestBodyFuelEfficiency model constructor.
     * @property {module:model/AllOfHereRequestBodyFuelEfficiency}
     */
    AllOfHereRequestBodyFuelEfficiency,

    /**
     * The AllOfHereRequestBodyHos model constructor.
     * @property {module:model/AllOfHereRequestBodyHos}
     */
    AllOfHereRequestBodyHos,

    /**
     * The AllOfHereRequestBodyTo model constructor.
     * @property {module:model/AllOfHereRequestBodyTo}
     */
    AllOfHereRequestBodyTo,

    /**
     * The AllOfHereRequestBodyTruck model constructor.
     * @property {module:model/AllOfHereRequestBodyTruck}
     */
    AllOfHereRequestBodyTruck,

    /**
     * The AllOfHereRequestBodyVehicleType model constructor.
     * @property {module:model/AllOfHereRequestBodyVehicleType}
     */
    AllOfHereRequestBodyVehicleType,

    /**
     * The AllOfHereResponseSummaryFuelEfficiency model constructor.
     * @property {module:model/AllOfHereResponseSummaryFuelEfficiency}
     */
    AllOfHereResponseSummaryFuelEfficiency,

    /**
     * The AllOfHereResponseSummaryVehicleType model constructor.
     * @property {module:model/AllOfHereResponseSummaryVehicleType}
     */
    AllOfHereResponseSummaryVehicleType,

    /**
     * The AnyOfbody model constructor.
     * @property {module:model/AnyOfbody}
     */
    AnyOfbody,

    /**
     * The AsyncResponse model constructor.
     * @property {module:model/AsyncResponse}
     */
    AsyncResponse,

    /**
     * The Body model constructor.
     * @property {module:model/Body}
     */
    Body,

    /**
     * The Body1 model constructor.
     * @property {module:model/Body1}
     */
    Body1,

    /**
     * The Cost model constructor.
     * @property {module:model/Cost}
     */
    Cost,

    /**
     * The DateTime model constructor.
     * @property {module:model/DateTime}
     */
    DateTime,

    /**
     * The Direction model constructor.
     * @property {module:model/Direction}
     */
    Direction,

    /**
     * The DirectionPosition model constructor.
     * @property {module:model/DirectionPosition}
     */
    DirectionPosition,

    /**
     * The Driver model constructor.
     * @property {module:model/Driver}
     */
    Driver,

    /**
     * The FuelEfficiency model constructor.
     * @property {module:model/FuelEfficiency}
     */
    FuelEfficiency,

    /**
     * The GeoCordinates model constructor.
     * @property {module:model/GeoCordinates}
     */
    GeoCordinates,

    /**
     * The GmapRequestBody model constructor.
     * @property {module:model/GmapRequestBody}
     */
    GmapRequestBody,

    /**
     * The GmapResponse model constructor.
     * @property {module:model/GmapResponse}
     */
    GmapResponse,

    /**
     * The GmapRouteResponse model constructor.
     * @property {module:model/GmapRouteResponse}
     */
    GmapRouteResponse,

    /**
     * The HereRequestBody model constructor.
     * @property {module:model/HereRequestBody}
     */
    HereRequestBody,

    /**
     * The HereResponse model constructor.
     * @property {module:model/HereResponse}
     */
    HereResponse,

    /**
     * The HereResponseSummary model constructor.
     * @property {module:model/HereResponseSummary}
     */
    HereResponseSummary,

    /**
     * The HereResponseSummaryFuelPrice model constructor.
     * @property {module:model/HereResponseSummaryFuelPrice}
     */
    HereResponseSummaryFuelPrice,

    /**
     * The HosData model constructor.
     * @property {module:model/HosData}
     */
    HosData,

    /**
     * The HosReq model constructor.
     * @property {module:model/HosReq}
     */
    HosReq,

    /**
     * The HosResponse model constructor.
     * @property {module:model/HosResponse}
     */
    HosResponse,

    /**
     * The HosResponseSummary model constructor.
     * @property {module:model/HosResponseSummary}
     */
    HosResponseSummary,

    /**
     * The HosResponseSummaryTotalDistance model constructor.
     * @property {module:model/HosResponseSummaryTotalDistance}
     */
    HosResponseSummaryTotalDistance,

    /**
     * The HosResponseSummaryTotalDriveDuration model constructor.
     * @property {module:model/HosResponseSummaryTotalDriveDuration}
     */
    HosResponseSummaryTotalDriveDuration,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The InlineResponse2001 model constructor.
     * @property {module:model/InlineResponse2001}
     */
    InlineResponse2001,

    /**
     * The InlineResponse200Route model constructor.
     * @property {module:model/InlineResponse200Route}
     */
    InlineResponse200Route,

    /**
     * The Location model constructor.
     * @property {module:model/Location}
     */
    Location,

    /**
     * The OneOfGmapRequestBodyDepartureTime model constructor.
     * @property {module:model/OneOfGmapRequestBodyDepartureTime}
     */
    OneOfGmapRequestBodyDepartureTime,

    /**
     * The OneOfHereRequestBodyDepartureTime model constructor.
     * @property {module:model/OneOfHereRequestBodyDepartureTime}
     */
    OneOfHereRequestBodyDepartureTime,

    /**
     * The OneOfLocation model constructor.
     * @property {module:model/OneOfLocation}
     */
    OneOfLocation,

    /**
     * The OneOfinlineResponse2001 model constructor.
     * @property {module:model/OneOfinlineResponse2001}
     */
    OneOfinlineResponse2001,

    /**
     * The PlaceId model constructor.
     * @property {module:model/PlaceId}
     */
    PlaceId,

    /**
     * The Rates model constructor.
     * @property {module:model/Rates}
     */
    Rates,

    /**
     * The Route model constructor.
     * @property {module:model/Route}
     */
    Route,

    /**
     * The RouteLocation model constructor.
     * @property {module:model/RouteLocation}
     */
    RouteLocation,

    /**
     * The RouteResponse model constructor.
     * @property {module:model/RouteResponse}
     */
    RouteResponse,

    /**
     * The RouteResponseSummary model constructor.
     * @property {module:model/RouteResponseSummary}
     */
    RouteResponseSummary,

    /**
     * The RouteResponseSummaryDiffs model constructor.
     * @property {module:model/RouteResponseSummaryDiffs}
     */
    RouteResponseSummaryDiffs,

    /**
     * The RouteResponseSummaryDistance model constructor.
     * @property {module:model/RouteResponseSummaryDistance}
     */
    RouteResponseSummaryDistance,

    /**
     * The RouteResponseSummaryDuration model constructor.
     * @property {module:model/RouteResponseSummaryDuration}
     */
    RouteResponseSummaryDuration,

    /**
     * The Stop model constructor.
     * @property {module:model/Stop}
     */
    Stop,

    /**
     * The SyncResponse model constructor.
     * @property {module:model/SyncResponse}
     */
    SyncResponse,

    /**
     * The SyncResponseRoute model constructor.
     * @property {module:model/SyncResponseRoute}
     */
    SyncResponseRoute,

    /**
     * The SyncResponseSummary model constructor.
     * @property {module:model/SyncResponseSummary}
     */
    SyncResponseSummary,

    /**
     * The TeritoryMielageRes model constructor.
     * @property {module:model/TeritoryMielageRes}
     */
    TeritoryMielageRes,

    /**
     * The TeritoryMielageResInner model constructor.
     * @property {module:model/TeritoryMielageResInner}
     */
    TeritoryMielageResInner,

    /**
     * The Timestamp model constructor.
     * @property {module:model/Timestamp}
     */
    Timestamp,

    /**
     * The Toll model constructor.
     * @property {module:model/Toll}
     */
    Toll,

    /**
     * The Truck model constructor.
     * @property {module:model/Truck}
     */
    Truck,

    /**
     * The VehicleType model constructor.
     * @property {module:model/VehicleType}
     */
    VehicleType,

    /**
    * The GPSTracestracksApi service constructor.
    * @property {module:api/GPSTracestracksApi}
    */
    GPSTracestracksApi,

    /**
    * The OriginAndDestinationPairApi service constructor.
    * @property {module:api/OriginAndDestinationPairApi}
    */
    OriginAndDestinationPairApi,

    /**
    * The RoutePolylineApi service constructor.
    * @property {module:api/RoutePolylineApi}
    */
    RoutePolylineApi
};
